### ISSUE TITLE
Docker User

### ISSUE THREAD

**Issue by Exadra37** [CrowdHailer/Tokumei#38]
I see in [this Readme](https://github.com/CrowdHailer/Tokumei/blob/master/app/README.md#usage) an alert to use chown in Linux, but we can get away with it if the Docker image uses the same user UID:GID of the Linux OS.

To achieve this we create an user `elixir` in the docker image with `uid:gid` equal to `1000:1000`, that usually is the same used in our PCs or Laptops if we are logged with the first user created in the Linux OS for us.

```Dockerfile
FROM elixir

ARG CONTAINER_USER='elixir'

RUN  useradd -m -u 1000  "${CONTAINER_USER}"

# this will make the container to run under user elixir with uid:gid 1000:1000
USER "${CONTAINER_USER}"
```

My Dockerfile using the above approach can be seens [here](https://gitlab.com/exadra37-learning/programming-elixir-1.3-book/blob/master/docker/Dockerfile#L32). 

Another approach is to start the container like `sudo docker run -v $PWD:/dir image-name  -u $UID:$GID  command-name`. Same can be done from a docker compose file.

Any of the above approaches will eliminate permissions conflicts between the container and our machine when mapping volumes.

> PS: I have not used this package yet, just trying to help with the Docker tip.

**Comment by CrowdHailer** [comment]
Awesome, thanks for the pointers, I will try both these approaches. I think wrapping it up in the dockerfile would be best. Will any of these changes cause problems for mac users? mac users didn't originally have the ownership problems

**Comment by Exadra37** [comment]
Not a Mac user, but under the hood  they are running Docker in a Linux Virtual Environment,  therefore that emulation may take care of the permissions issues...

**Comment by CrowdHailer** [comment]
I have not managed to make this work. I believe that the mix.archive is getting installed to the wrong user and when I change the user as described above before building the archive I get permission errors

**Comment by Exadra37** [comment]
Any operations made before change the user will be done as the root user.

Can you give a link to Dockerfile?

**Comment by CrowdHailer** [comment]
This is the [Dockerfile](https://github.com/CrowdHailer/Tokumei/blob/master/embark/Dockerfile)
 
If I change the user after line 11, then, when running the container later then the mix task `embark` cannot be found.
```
~/Projects/Tokumei (master *% u=)$ docker run -v $PWD:/tmp tokumei/embark my_app2
** (Mix) The task "embark" could not be found
```

If I change the user before line 9, then there is an error copying things into the container.
```
Step 8/10 : RUN mix compile && mix archive.build && mix archive.install --force
 ---> Running in 348f5a91191c
** (File.Error) could not make directory (with -p) "/installer/_build/dev/lib/embark": no such file or directory
    (elixir) lib/file.ex:236: File.mkdir_p!/1
```
