### ISSUE TITLE
SPA Example

### ISSUE THREAD

**Issue by joshua1** [CrowdHailer/Tokumei#46]
Hi @CrowdHailer ,
Can you include an SPA example say for the chat sample where http/2 streams are used via javascript with the backend APIs
Thanks

**Comment by CrowdHailer** [comment]
Hi,

Not in the short term. I have a lot things I'm running through at the moment. But I would welcome such a PR. I think that if a page is served over HTTP/2 then the javascript request use it as well.

For a streaming API to the browser you can check out https://html.spec.whatwg.org/#server-sent-events which is what the example currently uses. There are JS hooks at this point
